import:
  - "market.yaml"   # exit North
  - "../items/misc.yaml"

room:
  beach:
    name: "Tranquil Azure Playa"
    description: "Calm azure water laps at warm, pale sand. The only sound beyond the waves is an old man in the shade of a rock, muttering secrets he has almost certainly already forgotten."
    exits:
      North: "room.market"
    npc:
      - "npc.old_man"

npc:
  old_man:
    name: "Enigmatix"
    dialog:
      default:
        - "Hello adventurer!"
        - "It's a beautiful day for fishing, isn't it?"
      quest.lostbook.0:
        - "The last page of his book? Why would I have it? Is it because I'm old, is that it? Always the same thing. Go check out Cinematix at the market."
      quest.brainstorming.0:
       - "I have a French riddle for you. Give me the right answer (in French) to win a wonderful sacred seashell."
       - "Listen carefully:"
       - "Du repos des humains, implacable ennemi,"
       - "J'ai rendu mille amants envieux de mon sort,"
       - "Je me repais de sang et je trouve ma vie,"
       - "Dans les bras de celui qui recherche ma mort."
      quest.brainstorming.1:
       - "I have a French riddle for you. Give me the right answer (in French) to win a wonderful sacred seashell."
       - "Listen carefully:"
       - "Du repos des humains, implacable ennemi,"
       - "J'ai rendu mille amants envieux de mon sort,"
       - "Je me repais de sang et je trouve ma vie,"
       - "Dans les bras de celui qui recherche ma mort."
      quest.brainstorming.2:
        - "Unbelievable! You're amazing! You won this wonderful sacred seashell!"
    kind: Citizen
    quest: "quest.brainstorming"

quest:
  brainstorming:
    name: "Guess"
    description: "Find the answer."
    reward: "item.sacred_seashell"
    goals:
      - Talk:
          dialog: "npc.old_man.dialog.quest.brainstorming.0"
      - Answer:
          answer: "moustique"
          room: "room.beach"
      - Talk:
          dialog: "npc.old_man.dialog.quest.brainstorming.2"