import:
  - "city_square.yaml"   # exit North
  - "parc.yaml"          # exit East
  - "beach.yaml"         # exit South
  - "../items/potions.yaml"   # inventaire de seller

room:
  market:
    name: "The Artisan Plaza"
    description: "A bustling plaza of stalls and hand-painted signs, each one shouting a bargain louder than the last. Somewhere in the din, a merchant is already smashing his prices to splinters."
    exits:
      North: "room.city_square"
      East: "room.parc"
      South: "room.beach"
    npc:
      - "npc.seller"
      - "npc.citizen_3"
      - "npc.citizen_4"

npc:
  seller:
    name: "Oncassléprix"
    dialog:
      default:
        - "Come on over, ladies and gentlemen! My cheese smells wonderful! Come taste it and experience a culinary orgasm!"
    kind:
      Merchant:
        gold: 45
        inventory:
          - "item.strawberry"
          - "item.orange"
          - "item.bread"
          - "item.cheese"

  citizen_3:
    name: "Alavavix"
    dialog:
      default:
        - "Have you heard about those runaway teens? I've always said that boy was a bad influence."
        - "The guard will tell you more."
    kind: Citizen

  citizen_4:
    name: "Cinematix"
    dialog:
      default:
        - "That's all anyone is talking about in the village square: their running away. I find it sad that such a sensible boy would let himself be influenced by a girl of ill repute."
        - "The guard will tell you more."
      quest.lostbook.1:
        - "Yes I have her last page. She always used to say that books are better than movies. I wanted to play a prank on her. Nobody can delete the last 5 minutes of my movie. But with a book, all you have to do is tear out a page. The joke has gone on long enough, though. Take this page and bring it back to her."
    kind: Citizen
