import:
  - "mine.yaml"          # exit North
  - "blacksmith.yaml"    # exit South
  - "../items/misc.yaml"      # loot des goblins
  - "../enemies/enemies.yaml"

room:
  quarry:
    name: "The Ancient Pit"
    description: "An abandoned quarry of scattered rock, crumbling ruins, and the bones of animals that took the wrong shortcut. In the far corner, three goblins loiter before the entrance to an old mine, doing their very best to look like guards."
    exits:
      North: "room.mine"
      South: "room.blacksmiths_shop"
    npc:
      - "npc.goblins"
