item:
  shield:
    name: "You_shall_not_pass"
    price: 25
    kind:
      Armor:
        protection: 20

  helmet:
    name: "Helmetique"
    price: 15
    kind:
      Armor:
        protection: 10

  breastplate:
    name: "Plot Armor"
    price: 18
    kind:
      Armor:
        protection: 15
