item:
  gold:
    name: "Gold"
    price: 1
    kind: Miscellaneous

  goblin_tooth:
    name: "Goblin Tooth"
    price: 8
    kind: Miscellaneous

  sacred_seashell:
    name: "Sacred Seashell"
    price: 8
    kind: QuestItem

  golden_token:
    name: "Golden Token"
    price: 8
    kind: QuestItem
