import:
  - "items.yaml"
  - "quests.yaml"

npc:
  city_gard:
    name: "Haltlarix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen
    quest: "quest.test"

  bar_owner:
    name: "Grossbarrix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
      quest.test.1:
        - "Multi npc quest"
    kind:
      Merchant:
        gold: 45
        inventory:
          - "item.ale"
          - "item.pint"
          - "item.peanuts"

  client_1:
    name: "Nésousix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  client_2:
    name: "Spacix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  citizen_3:
    name: "Alavavix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  citizen_4:
    name: "Cinematix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  citizen_5:
    name: "Iwanttobreakfrix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  citizen_6:
    name: "Soirénetflix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  dealer:
    name: "Donnetonfrix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  farmer:
    name: "Sanpesticix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  cow:
    name: "Bigtastix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  seller:
    name: "Oncassléprix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind:
      Merchant:
        gold: 45
        inventory:
          - "item.strawberry"
          - "item.orange"

  old_man:
    name: "Enigmatix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  bookseller:
    name: "Damducédéix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind: Citizen

  blacksmith:
    name: "Métallurgix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind:
      Merchant:
        gold: 45
        inventory:
          - "item.sword"
          - "item.shield"
          - "item.helmet"

  goblins:
    name: "Sansabrix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind:
      Enemy:
        hp: 2000
        max_hp: 2000
        damages: 50
        loot:
          - "item.gold"
        defeated: false

  h:
    name: "Sansabrix"
    dialog:
      default:
        - "Stay safe, traveler."
        - "The roads can be dangerous."
    kind:
      Enemy:
        hp: 2000
        max_hp: 2000
        damages: 50
        loot:
          - "item.gold"
        defeated: false
