import:
  - "items.yaml"
  - "npc.yaml"

quest:
  test:
    name: "Test"
    description: "Test quest"
    reward: "item.ale"
    goals:
      - Collect:
          item: "item.ale"
          amount: 1
      - Talk:
          dialog: "npc.bar_owner.dialog.quest.test.1"
