import:
  - "npc.yaml"
  - "items.yaml"

room:
  city_square:
    name: "The Answer Place"
    description: "A small, quiet square with a bulletin board and a tavern to the north."
    exits:
      North: "room.tavern"
      East: "room.blacksmith's_shop"
      West: "room.farm"
      South: "room.market"
    npc:
      - "npc.city_gard"
      - "npc.h"
    items:
      - "item.ale"
      - "item.orange"
      - "item.shield"

  tavern:
    name: "The Awesome Pub"
    description: "A warm and lively tavern. From outside, we can hear the clinking of glasses, off-key singing, and hearty, joyful laughter."
    exits:
      South: "room.city_square"
      North: "room.game_room"
    npc:
      - "npc.bar_owner"
      - "npc.client_1"
      - "npc.client_2"

  game_room:
    name: "The Ace Play"
    description: "A room restricted to those 18 and older, with several gaming tables. In the background, we can see another room hidden behind a pink curtain, but it’s inaccessible without the DLC."
    exits:
      South: "room.tavern"
    npc:
      - "npc.dealer"

  farm:
    name: "The Abundant Pasture"
    description: "A charming little farm with fields and animals. A farmer is there with his cow."
    exits:
      East: "room.city_square"
    npc:
      - "npc.farmer"
      - "npc.cow"

  market:
    name: "The Artisan Plaza"
    description: "A charming little market."
    exits:
      North: "room.city_square"
      East: "room.parc"
      South: "room.beach"
    npc:
      - "npc.seller"
      - "npc.citizen_3"
      - "npc.citizen_4"

  beach:
    name: "Tranquil Azure Playa"
    description: "A charming little beach. The sea is calm, the sand is warm beneath our feet, and there’s just an old man muttering to himself in the shade of a rock."
    exits:
      North: "room.market"
    npc:
      - "npc.old_man"

  parc:
    name: "The Amazing Parc"
    description: "A charming little park filled with children playing under their parents' watchful eyes. There's even a reading corner for those who prefer a quieter spot."
    exits:
      North: "room.blacksmith's_shop"
      West: "room.market"
    npc:
      - "npc.bookseller"
      - "npc.citizen_5"
      - "npc.citizen_6"

  blacksmith's_shop:
    name: "Tongs, Anvils & Pincers"
    description: "A blacksmith's shop where the sounds of a hammer striking red-hot metal, a blade heated to white-hot and plunged into cold water, and a bellows stoking the roaring flames echo through the air."
    exits:
      North: "room.quarry"
      East: "room.forest"
      South: "room.parc"
      West: "room.city_square"
    npc:
      - "npc.blacksmith"

  forest:
    name: "The Awkward Patch"
    description: "A foreboding forest. Its twisted trees and flocks of crows perched on bare branches—despite the season—create an unsettling atmosphere."
    exits:
      West: "room.blacksmith's_shop"
      # East: "room.dunjon"

  quarry:
    name: "The Ancient Pit"
    description: "An abandoned quarry. There are only scattered rocks, the ruins of an old building, and animal bones. In the far corner, you can see three goblins who appear to be guarding the entrance to an old mine."
    exits:
      North: "room.mine"
      South: "room.blacksmith's_shop"
    npc:
      - "npc.goblins"

  mine:
    name: "The Abandoned Prospect"
    description: "A dark, damp mine. All you can hear is the sound of water dripping from the stalactites and the flapping of bats’ wings. In the center stands an old mine car, still on its tracks."
    exits:
      South: "room.quarry"
