spawn_point: "room.city_square"
gambling_room: "room.game_room"
dungeon_entrance: "room.forest"

import:
  - "config/rooms/city_square.yaml"
  - "config/rooms/tavern.yaml"
  - "config/rooms/game_room.yaml"
  - "config/rooms/farm.yaml"
  - "config/rooms/market.yaml"
  - "config/rooms/beach.yaml"
  - "config/rooms/parc.yaml"
  - "config/rooms/blacksmith.yaml"
  - "config/rooms/forest.yaml"
  - "config/rooms/quarry.yaml"
  - "config/rooms/mine.yaml"
