#[derive(Debug, Clone, PartialEq)]
pub enum PendingAction {
    None,
    Gold,
	Npcs,
	Npc,
	Flee,
	Consume(String),
    Talk(String),
    Drop(String),
    Take(String),
	Auth,
	GroupCreate(String),
	GroupJoin(String),
	GroupLeave(String),
	GroupInvite(String),
	SendChat(String, String),
	ClientLook,
	Look,
	Status,
	ClientStatus,
	Move,
	Who,
	Attack(String),
	Inventory,
	ClientInventory,
	Quest,
	Items
}