use crate::structures::quest_view::QuestStatus;

#[derive(Debug, Clone, PartialEq)]
pub enum PendingAction {
    None,
    Gold,
    ClientGold,
    Npcs,
    DungeonNpcs,
    Sell(String),
    Buy(String),
    Npc,
    Flee,
    Consume(String),
    Talk(String),
    Drop(String),
    Take(String),
    Auth,
    GroupCreate(String),
    GroupJoin(String),
    GroupLeave(String),
    GroupInvite(String),
    SendChat(String, String),
    ClientLook,
    DungeonLook,
    MoveLook,
    Look,
    Rooms,
    Status,
    ClientStatus,
    Move,
    Who,
    Attack(String),
    Inventory,
    ClientInventory,
    Quest,
    Quests,
    ClientQuests,
    QuestInfo(String, QuestStatus),
    Items,
    DungeonItems,
	Dices(String),
	Slot,
	DungeonCreate,
	DungeonJoin,
}
