import:
  - "../items/misc.yaml"
  - "../items/armors.yaml"
  - "../items/weapons.yaml"
  - "../items/potions.yaml"

npc:
  goblins:
    name: "Sansabrix"
    dialog:
      default:
        - "Turn back, human. This mine is ours."
    kind:
      Enemy:
        hp: 120
        max_hp: 120
        damages: 15
        loot:
          - "item.gold"
          - "item.goblin_tooth"
        defeated: false

  dragon:
    name: "Thermostadix"
    dialog:
      default:
        - "Do you have a light?"
    kind:
      Enemy:
        hp: 300
        max_hp: 300
        damages: 35
        loot:
          - "item.gold"
          - "item.gold"
          - "item.sword"
          - "item.helmet"
        defeated: false

  politician:
    name: "Fourberix"
    dialog:
      default:
        - "I can explain everything, I promise!"
    kind:
      Enemy:
        hp: 200
        max_hp: 120
        damages: 4
        loot:
          - "item.gold"
          - "item.gold"
          - "item.gold"
          - "item.pint"
        defeated: false